version: '2.2'
services:
  tron-node:
    image: caeldock/tron-node
    container_name: tron-node
    ports:
      - 18888:18888
      - 50051:50051
    tty: true
    command: ./gradlew run -Pwitness 
